package carsharing;

public enum PROGRAM_STATUS {
    STOPPED,
    START_MENU,
    MANAGER_MENU,
    SELECT_CUSTOMER_MENU,
    CREATE_CUSTOMER_MENU,
    CUSTOMER_MENU,
    SELECT_COMPANY_MENU,
    CREATE_COMPANY_MENU,
    COMPANY_MENU,
    CREATE_CAR_MENU,
    RENTING_A_CAR;
}
